<?php

return [
    'version' => '1.0.0',
    'site_title' => 'Domain List',
    'owner' => 'Fabian Ternis',

    'domains' => [

        // ── EXPIRED ──────────────────────────────────────────────────────────

        'xp-craft.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'darkangel-mc.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'xp-host.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'ebay-konto.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'citycraft-nw.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'mail-free.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'michaelninder.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'xp-link.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'dogwaterdev.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => 'Re-registered. Home of <a href="https://github.com/DogWaterDev" target="_blank" rel="noopener">DogWaterDev</a>.',
        ],
        'xp-node.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'dexify.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'xp-cloud.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'code-trainer.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'a-sub.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'b-sub.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'hhgkl.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'citycraft-smp.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'quizhive.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'bank-of-europe.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'craftattack.xyz' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'euromc.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'xp-h.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'louixch.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => 'Personal domain for Louixch.',
        ],
        'europehost.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'xp-l.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'sub2.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'domaingen.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'webstruct.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'mcservertools.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'xphost.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'mcpractice.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'novastack.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'flexistack.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'pelicanhost.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'axiohost.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'axiohost.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'city-craft.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'xp-domains.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'xp-domain.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'xpsystems.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'xpsys.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'xfolio.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'eupractice.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'soulnode.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'expired',
            'description' => null,
        ],
        'eudomains.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => 'Domain management services. <a href="https://github.com/eudomains" target="_blank" rel="noopener">GitHub</a>.',
        ],
        'bank-of-germany.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'schulchat-rlp.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'nerax.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'anlink.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'mchost24.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        '24mc.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'schulkampus-rlp.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'bildungslogin-rlp.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'xp-mail.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'pythonhub.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'xmage.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'imagu.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'dcpic.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => 'Discord picture service. <a href="https://github.com/europehost/dsc.pics" target="_blank" rel="noopener">GitHub</a>.',
        ],
        'swiftshare.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'pyshop.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'eushare.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'ptero01.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'epyc01.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'ryzen01.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'xpgames.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'csslib.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        '2note.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'burgermc.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'fternis.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => 'Short personal domain. Visit at <a href="https://fternis.de/" target="_blank" rel="noopener">fternis.de</a>.',
        ],
        'bildungsbereich-rlp.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'xp-ad.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'laravel-tutorial.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'gehirn-weg.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'staatliches-heinrich-heine-gymnasium-kaiserslautern.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'spielefrei.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'yourlink.app' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'mcserver.lol' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'dsc.pics' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => 'Discord image service. <a href="https://github.com/europehost/dsc.pics" target="_blank" rel="noopener">GitHub</a>.',
        ],
        'mtex.dev' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => '<a href="https://github.com/MTEX-dev" target="_blank" rel="noopener">MTEX-dev on GitHub</a>.',
        ],
        'gimy.site' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => '<a href="https://github.com/MTEX-dev/gimy-site" target="_blank" rel="noopener">GitHub – gimy-site</a>.',
        ],
        'urlk.app' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'twch.pics' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'fabianternis.dev' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => 'Personal developer domain.',
        ],
        'fabianternis.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => 'Main personal domain.',
        ],
        'pleasehireme.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'getmy.name' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'getmy.blog' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'fabian-ternis.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => 'Personal domain.',
        ],
        'mysocials.me' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'getsocials.link' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'linkmy.name' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'kaufenhof.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => 'Managed on behalf of a client.',
        ],
        'woistdasdrachenei.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'ivoternis.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => 'Personal domain for <a href="https://github.com/IvoTernis" target="_blank" rel="noopener">IvoTernis</a>.',
        ],
        'heimatverein-floersheim-dalsheim.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        '192-168-0-1.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => 'Note: 127-0-0-1.de was already taken.',
        ],
        'sandbox-api.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'api-sandbox.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => '<a href="https://github.com/api-sandbox-DE" target="_blank" rel="noopener">GitHub – api-sandbox-DE</a>.',
        ],
        'hhg-kl.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => null,
        ],
        'mail-free.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => '<a href="https://github.com/mail-free" target="_blank" rel="noopener">GitHub – mail-free</a>.',
        ],
        'ternis.eu' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => '<a href="https://github.com/ternis-eu" target="_blank" rel="noopener">GitHub – ternis-eu</a>.',
        ],
        'xpsystems.de' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => '<a href="https://github.com/xpsystems" target="_blank" rel="noopener">GitHub – xpsystems</a>.',
        ],
        'eu-data.org' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => '<a href="https://github.com/eu-data-org" target="_blank" rel="noopener">GitHub – eu-data-org</a>.',
        ],
        'eu-search.org' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => '<a href="https://github.com/eu-search-org" target="_blank" rel="noopener">GitHub – eu-search-org</a>.',
        ],
        'web-search.org' => [
            'from'        => null,
            'to'          => null,
            'status'      => 'active',
            'description' => '<a href="https://github.com/web-searchorg" target="_blank" rel="noopener">GitHub – web-searchorg</a>.',
        ],

    ],
];